[package]
name = "ps-promise"
version = "0.1.0-1"
description = "Promise-like owned futures"
license = "GPL-3.0-or-later"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
thiserror = "2.0.12"
