[package]
name = "ps-promise"
version = "0.1.0-9"
edition = "2021"
description = "Promise-like owned futures"
license = "GPL-3.0-or-later"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
